name: learner
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - transformers
  - scikit-learn
  - numpy
  - pandas
  - requests
  - pip
  - cudatoolkit=11.8
  - numba
  - pip:
    - accelerate
    - sentencepiece
    - safetensors